sudo: false

language: go
go:
  - 1.14.x
  - 1.13.x

before_script:
  - go get golang.org/x/lint/golint

script:
  - go build ./...
  - golint ./...
  - go test -v ./...

after_script:
  - F=$(go fmt ./...); if [ ! -z "$F" ]; then echo "Please gofmt for"$'\n'"$F"; exit 1; fi
